import { expect, type Locator, type Page } from "@playwright/test";
import type { Product } from "../../test-data/qa-practice/cart/data";

export class ProductsPage {
  readonly heading: Locator;
  readonly itemColumn: Locator;
  readonly priceColumn: Locator;
  readonly quantityColumn: Locator;
  readonly total: Locator;
  readonly purchaseButton: Locator;
  readonly message: Locator;
  private mockedProducts: Product[] = [];

  constructor(readonly page: Page) {
    this.heading = page.getByRole("heading", { name: "SHOPPING CART" });
    this.itemColumn = page.getByText("ITEM", { exact: true });
    this.priceColumn = page.getByText("PRICE", { exact: true });
    this.quantityColumn = page.getByText("QUANTITY", { exact: true });
    this.total = page.locator(".cart-total-price");
    this.purchaseButton = page.getByRole("button", { name: "PURCHASE" });
    this.message = page.locator("#message");
  }

  async mockProducts(products: Product[]): Promise<void> {
    this.mockedProducts = products;
    await this.page.route("**/products?limit=10&skip=0", async (route) => {
      await route.fulfill({
        headers: {
          "access-control-allow-origin": "*"
        },
        json: {
          products,
          total: products.length,
          skip: 0,
          limit: 10
        }
      });
    });
  }

  async goto(): Promise<void> {
    await this.page.goto("/products_list");
    await this.renderMockedProductsIfNeeded();
    await this.waitForProducts();
  }

  async waitForProducts(): Promise<void> {
    await this.addToCartButtonFor("Apple iPhone 12, 128GB, Black").waitFor();
  }

  async expectInitialCart(): Promise<void> {
    await expect(this.heading).toBeVisible();
    await expect(this.itemColumn).toBeVisible();
    await expect(this.priceColumn).toBeVisible();
    await expect(this.quantityColumn).toBeVisible();
    await expect(this.total).toHaveText("$0");
  }

  async expectProductVisible(product: Product): Promise<void> {
    await expect(this.productCard(product.title)).toContainText(product.title);
    await expect(this.productCard(product.title)).toContainText(`$${product.price}`);
  }

  async addProduct(product: Product): Promise<void> {
    await this.addToCartButtonFor(product.title).click();
  }

  async addProducts(products: Product[]): Promise<void> {
    for (const product of products) {
      await this.addProduct(product);
    }
  }

  async expectCartLine(product: Product, quantity: number): Promise<void> {
    const line = this.cartLine(product.title);

    await expect(line).toContainText(product.title);
    await expect(line).toContainText(`$${product.price}`);
    await expect(this.quantityInput(product.title)).toHaveValue(String(quantity));
  }

  async expectTotal(expectedTotal: number): Promise<void> {
    await expect.poll(async () => this.currentTotal()).toBe(expectedTotal);
  }

  async expectPurchaseReady(): Promise<void> {
    await expect(this.purchaseButton).toBeEnabled();
  }

  async purchase(): Promise<void> {
    await this.purchaseButton.click();
  }

  async expectPurchaseCompleted(totalLabel: string): Promise<void> {
    await expect(this.message).toContainText(`Congrats! Your order of ${totalLabel}`);
  }

  async currentTotal(): Promise<number> {
    const text = await this.total.innerText();
    return Number(text.replace("$", "").replace(",", ""));
  }

  private productCard(title: string): Locator {
    // The demo product cards have no roles, labels, or data-testid values.
    return this.page.locator(".shop-item").filter({ hasText: title });
  }

  private addToCartButtonFor(title: string): Locator {
    return this.productCard(title).getByRole("button", { name: "ADD TO CART" });
  }

  private cartLine(title: string): Locator {
    // Cart rows are generated by the app script without semantic row roles or test IDs.
    return this.page.locator(".cart-row").filter({ hasText: title });
  }

  private quantityInput(title: string): Locator {
    return this.cartLine(title).locator(".cart-quantity-input");
  }

  private async renderMockedProductsIfNeeded(): Promise<void> {
    if (this.mockedProducts.length === 0) {
      return;
    }

    await this.page.waitForFunction(() => typeof window.addItemToCart === "function" && typeof window.updateCartTotal === "function");
    await this.page.evaluate((products) => {
      const shopItemsContainer = document.querySelector(".shop-items");

      if (!shopItemsContainer) {
        throw new Error("Missing .shop-items container");
      }

      shopItemsContainer.innerHTML = "";

      for (const product of products) {
        const shopItem = document.createElement("div");
        shopItem.classList.add("shop-item");
        shopItem.innerHTML = `
          <span class="shop-item-title">${product.title}</span>
          <div class="shop-item-details">
            <span class="shop-item-price">$${product.price}</span>
            <button class="btn btn-primary shop-item-button" type="button">ADD TO CART</button>
          </div>`;
        shopItem.querySelector(".shop-item-button")?.addEventListener("click", () => {
          window.addItemToCart(product.title, `$${product.price}`);
          window.updateCartTotal();
        });
        shopItemsContainer.appendChild(shopItem);
      }
    }, this.mockedProducts);
  }
}

declare global {
  interface Window {
    addItemToCart(title: string, price: string): void;
    updateCartTotal(): void;
  }
}
